name: Generate Jörmungandr
on:
  # Run workflow automatically
  schedule:
    # Run every day at 00:00 UTC
    - cron: "0 0 * * *"
  
  # Allow manual workflow run (keep this for testing)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@master
        id: jormungandr-gif
        with:
          github_user_name: unlovdman
          # Update output paths to match your README references
          svg_out_path: output/github-contribution-grid-snake.svg
          svg_out_path_dark: output/github-contribution-grid-snake-dark.svg
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}